### ISSUE TITLE
Generate DAG for Graph evaluators is slow

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/SHIPs.jl#11]
@casv2 if you have some estimates for the larger basis sets?

**Comment by casv2** [comment]
For N=6, polydeg=18, # ~8K we're looking at around 1 hour on the HPC.
For N=8, polydeg=18, # ~10K we're looking at around 6 hours on the HPC.

**Comment by cortner** [comment]
@casv2  I've made some basic optimisations to the graph generation code:
```
#basis = 2135
graph construction: 0.806830 seconds

#basis = 4672
graph construction: 4.596158 seconds

#basis = 6856
graph construction: 17.415428 seconds

#basis = 16305
graph construction:  127.77 seconds
```
Not great but _a lot_ better. Please try it out!

This is currently on the margarita branch. (maybe the joke has passed and I should rename it `dev` ...)

**Comment by cortner** [comment]
I'm just going to leave this for a little while. But my guess is that the summer project with Matteo will show how to generate the graph with heuristic and without searching through all partitions.

**Comment by cortner** [comment]
So I'm closing this for now so I don't get distracted thinking about it as there are many more important things to do. If this becomes an issue again please re-open.
