### ISSUE TITLE
combine(IP,c) with c vector from disk

### ISSUE THREAD

**Issue by casv2** [JuliaMolSim/SHIPs.jl#5]
When reading a coefficients `c` vector from disk, `combine(IP, c)` should be converted from Any to Float64 first.

**Comment by cortner** [comment]
I don't see the problem in SHIPs. Does this happen when you read  some coefficients other than through just saving and loading a potential? I.e., something along the lines of  (pseudocode)
```
basis = constructmybasis(...)
c = fitthecoefficients(basis, data)
save(basis)
save(c)
basis = load()
c = load()
combine(basis, c)
```
? If this is the case, then I'm just going to be brutal and say it is the responsibility of the user to make sure the coefficients are converted correctly after reading from disk. 

The following little trick will do the conversion automagically:
```
identity.(c)
```

Please just re-open if I've misunderstood.

**Comment by cortner** [comment]
P.S.: I've inserted the `identity` trick into a few places to make life a little easier.
